### ISSUE TITLE
`contract_low_support` can contract leaf nodes

### ISSUE THREAD

**Issue by RuneBlaze** [niemasd/TreeSwift#18]
In the current code of `contract_low_support`, it is possible that leaf nodes will have label that is below threshold, and hence contracted (for example, "0" as a leaf label will be problematic).

https://github.com/niemasd/TreeSwift/blob/7a17f42005a04b47eb49a78b00302f9b4ebae588/treeswift/Tree.py#L229-L244

I think the easy fix should be only traverse the internal nodes. Let me know if this is something preferred as a PR.

**Comment by niemasd** [comment]
Thanks for catching that! Fixed in TreeSwift v1.1.19:

https://github.com/niemasd/TreeSwift/blob/352f74b0ca1e1728c1dfcba306a2a074334c3963/treeswift/Tree.py#L229-L249

I've added optional function parameters to select terminal vs. internal branches, and by default, it only will select internal branches
